"""Build design/components/lockup.generated.js from the official logo file.

    python design/scripts/build_lockup.py           write it
    python design/scripts/build_lockup.py --check   exit 1 when it differs from what the logo file gives

Source: brand/02_lockups/lockup_horizontal_transparent_light.svg, the approved lockup (hook + «КРЮК24» /
«ЭВАКУАТОР+», 04.10.2026). Its hook path and its two text lines are copied as they are: same positions, sizes and
letter-spacing. Only two things change: the embedded font block is dropped (the page loads the same brand fonts),
and the colours become CSS classes, so one artwork serves light and dark with the colours of tools/brand.py:
kr-l-hook (orange), kr-l-main (navy on light, white on dark), kr-l-sub (orange on light, soft orange on dark).
Nothing here draws a logo of its own; KryukMark only places this artwork.
"""
import json
import re
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parents[2]
LOGO = ROOT / "brand" / "02_lockups" / "lockup_horizontal_transparent_light.svg"
OUT = ROOT / "design" / "components" / "lockup.generated.js"
ORANGE, INK = "#EF5B00", "#13233A"


def build():
    src = LOGO.read_text(encoding="utf-8")
    body = re.sub(r"<style>.*?</style>", "", src, flags=re.S)
    body = body[body.index(">", body.index("<svg")) + 1:body.rindex("</svg>")]
    hook_t = re.search(r'<path transform="translate\(([\d.]+),([\d.]+)\) scale\(([\d.]+)\)"', body)
    x0, y0, k = (float(v) for v in hook_t.groups())
    hook_lines = (ROOT / "brand" / "00_hook_master" / "hook_path.txt").read_text(encoding="utf-8").split("\n")
    hook_w, hook_h = (float(v) for v in hook_lines[0].split())
    h = hook_h * k                                   # hook height in the file (120)
    vb = re.search(r'viewBox="0 0 ([\d.]+) ([\d.]+)"', src)
    w = float(vb.group(1)) - 2 * x0                  # the file pads the lockup equally on both sides
    parts = {
        'fill="%s" fill-rule="evenodd"' % ORANGE: 'class="kr-l-hook" fill-rule="evenodd"',
        'fill="%s" text-anchor="start">КРЮК24' % INK: 'class="kr-l-main" text-anchor="start">КРЮК24',
        'fill="%s">ЭВАКУАТОР' % ORANGE: 'class="kr-l-sub">ЭВАКУАТОР',
        '<tspan font-weight="700" fill="%s">+' % INK: '<tspan font-weight="700" class="kr-l-main">+',
    }
    for old, new in parts.items():
        if body.count(old) != 1:
            raise SystemExit("the logo file changed shape; update build_lockup.py (" + old + ")")
        body = body.replace(old, new)
    data = {"x": x0, "y": y0, "w": round(w, 3), "h": round(h, 3), "hookW": round(hook_w * k, 3), "svg": body}
    return ("/* KRYUK24 official lockup. GENERATED by design/scripts/build_lockup.py from brand/02_lockups/"
            "lockup_horizontal_transparent_light.svg (fonts dropped, colours as classes). Do not edit. */\n"
            "window.KryukLockup = %s;\n" % json.dumps(data, ensure_ascii=False, separators=(",", ":")))


def main():
    text = build()
    if "--check" in sys.argv[1:]:
        ok = OUT.exists() and OUT.read_text(encoding="utf-8") == text
        print("KRYUK24 LOGO ARTWORK: " + ("same as the logo file" if ok else "STALE, run design/scripts/build_lockup.py"))
        return 0 if ok else 1
    OUT.write_text(text, encoding="utf-8", newline="\n")
    print("lockup written:", OUT.relative_to(ROOT))
    return 0


if __name__ == "__main__":
    sys.exit(main())
