"""Build KRYUK24 design tokens from design/tokens/kryuk-tokens.source.json.

    python design/scripts/build_tokens.py           write kryuk.tokens.css and tokens.json
    python design/scripts/build_tokens.py --check   exit 1 when the generated files differ from the source

Outputs (never edited by hand):
    design/tokens/kryuk.tokens.css   custom properties: primitives, scales, light, dark, contrast scope, OS dark
    design/tokens/tokens.json        the same values as data
    design/components/hook.generated.js   the hook vector from brand/00_hook_master/hook_path.txt, for KryukMark
"""
import json
import re
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parents[2]
SRC = ROOT / "design" / "tokens" / "kryuk-tokens.source.json"
OUT_CSS = ROOT / "design" / "tokens" / "kryuk.tokens.css"
OUT_JSON = ROOT / "design" / "tokens" / "tokens.json"
HOOK_SRC = ROOT / "brand" / "00_hook_master" / "hook_path.txt"
OUT_HOOK = ROOT / "design" / "components" / "hook.generated.js"
REF = re.compile(r"^\{([a-z0-9-]+)\}$")


def resolve(value, primitives):
    m = REF.match(value)
    if not m:
        return value
    if m.group(1) not in primitives:
        raise SystemExit("unknown primitive reference: " + value)
    return "var(--%s)" % m.group(1)


def literal(value, primitives):
    m = REF.match(value)
    return primitives[m.group(1)] if m else value


def block(selector, pairs):
    lines = ["%s {" % selector] + ["  --%s: %s;" % (k, v) for k, v in pairs] + ["}"]
    return "\n".join(lines)


def build(src):
    p = src["primitives"]
    light = [(k, resolve(v, p)) for k, v in src["themes"]["light"].items()]
    dark = [(k, resolve(v, p)) for k, v in src["themes"]["dark"].items()]
    if [k for k, _ in light] != [k for k, _ in dark]:
        raise SystemExit("light and dark must define the same tokens in the same order")
    parts = [
        "/* KRYUK24 design tokens. GENERATED by design/scripts/build_tokens.py from kryuk-tokens.source.json. Do not edit. */",
        block(":root", list(p.items()) + list(src["scales"].items())),
        "/* Light is the default theme. */",
        block(':root,\n[data-theme="light"]', light),
        "/* Dark theme, and the dark navy contrast scope used inside either theme. */",
        block('[data-theme="dark"],\n.section-contrast', dark),
        "@media (prefers-color-scheme: dark) {\n" + block(':root:not([data-theme="light"])', dark).replace("\n", "\n  ").replace(":root:not", "  :root:not", 1) + "\n}",
    ]
    css = "\n\n".join(parts) + "\n"
    data = {
        "name": src["name"],
        "version": src["version"],
        "primitives": p,
        "scales": src["scales"],
        "themes": {t: {k: literal(v, p) for k, v in src["themes"][t].items()} for t in ("light", "dark")},
    }
    return css, json.dumps(data, ensure_ascii=False, indent=2) + "\n"


def build_hook():
    lines = HOOK_SRC.read_text(encoding="utf-8").split("\n")
    w, h = (float(v) for v in lines[0].split())
    d = lines[1].strip()
    return ("/* KRYUK24 hook vector. GENERATED by design/scripts/build_tokens.py from brand/00_hook_master/hook_path.txt. Do not edit. */\n"
            "window.KryukHook = %s;\n" % json.dumps({"w": w, "h": h, "d": d}, separators=(",", ":")))


def main():
    src = json.loads(SRC.read_text(encoding="utf-8"))
    css, data = build(src)
    hook = build_hook()
    if "--check" in sys.argv[1:]:
        stale = [str(f.relative_to(ROOT)) for f, text in ((OUT_CSS, css), (OUT_JSON, data), (OUT_HOOK, hook)) if not f.exists() or f.read_text(encoding="utf-8") != text]
        if stale:
            print("KRYUK24 TOKENS: STALE " + ", ".join(stale))
            return 1
        print("KRYUK24 TOKENS: up to date")
        return 0
    OUT_CSS.write_text(css, encoding="utf-8", newline="\n")
    OUT_JSON.write_text(data, encoding="utf-8", newline="\n")
    OUT_HOOK.write_text(hook, encoding="utf-8", newline="\n")
    print("KRYUK24 TOKENS: written (%d primitives, %d scales, %d theme tokens)" % (len(src["primitives"]), len(src["scales"]), len(src["themes"]["light"])))
    return 0


if __name__ == "__main__":
    sys.exit(main())
