"""One design source for the Armen portal and the operator page: design/tokens.

    python design/scripts/check_shared_design.py

Fails when the two pages stop agreeing with the tokens, so a change of the design is carried to both or CI is red:
  1. the portal's tokens.css is design/tokens/kryuk.tokens.css byte for byte (the portal loads that file itself);
  2. the portal's own style sheet and pages hold no colour value: every colour comes from a token;
  3. the portal's dark logo is the operator page's logo file byte for byte, and its fonts are the site's files;
  4. the operator page in KRYUK24 colours (runtime/wip/dashboard_colours/ops_views.py, a protected file made by
     make_patch.py) loads the same token file and font list from the portal's address; every grey and navy step of
     it is a reference to its token, and every value written in it as a fallback equals the token.
So one file, design/tokens/kryuk.tokens.css, served by the portal, colours both pages; a change of it reaches both
without touching either page. The fallbacks inside the operator page are the one thing regenerated by hand, and this
check is red until they are.
"""
import re
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parents[2]
PORTAL = ROOT / 'runtime' / 'armen_portal'
TOKENS = ROOT / 'design' / 'tokens' / 'kryuk.tokens.css'
PAGE = ROOT / 'runtime' / 'wip' / 'dashboard_colours' / 'ops_views.py'
# operator page variable -> design token
PALETTE = {'neutral-0': 'grey-0', 'neutral-50': 'grey-50', 'neutral-100': 'grey-100', 'neutral-200': 'grey-200',
           'neutral-300': 'grey-300', 'neutral-400': 'grey-400', 'neutral-500': 'grey-600', 'neutral-700': 'grey-700',
           'neutral-800': 'navy-800', 'neutral-900': 'navy-900', 'neutral-950': 'navy-950',
           'orange-300': 'orange-300', 'orange-350': 'orange-350', 'orange-400': 'orange-400', 'orange-500': 'orange-500',
           'orange-700': 'orange-700'}
SAME = {'logo-dark.webp': ROOT / 'runtime' / 'wip' / 'dashboard_colours' / 'kryuk-logo-dark.webp',
        'font-golos-cyrillic.woff2': ROOT / 'site' / 'assets' / 'fonts' / 'golos-400-cyrillic.woff2',
        'font-golos-latin.woff2': ROOT / 'site' / 'assets' / 'fonts' / 'golos-400-latin.woff2',
        'font-robotocond-700-cyrillic.woff2': ROOT / 'site' / 'assets' / 'fonts' / 'robotocond-700-cyrillic.woff2',
        'font-robotocond-700-latin.woff2': ROOT / 'site' / 'assets' / 'fonts' / 'robotocond-700-latin.woff2'}
COLOUR = re.compile(r'#[0-9a-fA-F]{3,8}\b|\brgba?\(|\bhsla?\(')

problems = []
if (PORTAL / 'tokens.css').read_bytes() != TOKENS.read_bytes():
    problems.append('runtime/armen_portal/tokens.css differs from design/tokens/kryuk.tokens.css: copy it again')
for name in ('style.css', 'fonts.css', 'index.html', 'login.html', 'app.js', 'login.js', 'theme.js'):
    for number, line in enumerate((PORTAL / name).read_text(encoding='utf-8').splitlines(), 1):
        found = COLOUR.search(line)
        if found:
            problems.append('%s line %d holds a colour value (%s): use a token' % (name, number, found.group(0)))
for name, source in SAME.items():
    if (PORTAL / name).read_bytes() != source.read_bytes():
        problems.append('runtime/armen_portal/%s differs from %s' % (name, source.relative_to(ROOT).as_posix()))
tokens = dict(re.findall(r'--([a-z]+-\d+):\s*(#[0-9A-Fa-f]{6});', TOKENS.read_text(encoding='utf-8')))
page = PAGE.read_text(encoding='utf-8')
for link in ('/operator/work/armen/tokens.css', '/operator/work/armen/fonts.css'):
    if page.count('<link rel="stylesheet" href="%s">' % link) != 1:
        problems.append('operator page: does not load %s' % link)
if 'var(--font-sans,' not in page:
    problems.append("operator page: the text font is not the tokens' font")
for variable, token in PALETTE.items():
    if variable == token:  # the same name as the token: the loaded file overrides the value written in the page
        values = set(v.lower() for v in re.findall(r'--%s:(#[0-9a-fA-F]{6})' % re.escape(variable), page))
    else:                  # another name: must be a reference to the token, with the token's value as the fallback
        values = set(v.lower() for v in re.findall(r'--%s:var\(--%s,(#[0-9a-fA-F]{6})\)' % (re.escape(variable), re.escape(token)), page))
    if not values:
        problems.append('operator page: --%s is not tied to the token --%s' % (variable, token))
    elif values != {tokens[token].lower()}:
        problems.append('operator page: the fallback of --%s is %s, the token --%s is %s' % (variable, sorted(values), token, tokens[token]))
for problem in problems:
    print('RED', problem)
if problems:
    sys.exit(1)
print('shared design: portal tokens equal the design tokens, no colour value in the portal, logo and fonts are the shared files, the operator page loads the same token file and its %d steps are tied to their tokens' % len(PALETTE))
